/**
 * @file eagle_task.h
 *
 * @brief This header file was generated by cantools version 44.1.0 Thu Oct  8 07:06:21 2026.
 *
 * @copyright Copyright (c) 2018-2019 Erik Moqvist
 *
 * @par License
 * The MIT License (MIT)
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use, copy,
 * modify, merge, publish, distribute, sublicense, and/or sell copies
 * of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
 * BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
 * ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

#ifndef EAGLE_TASK_H
#define EAGLE_TASK_H

#ifdef __cplusplus
extern "C" {
#endif

#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>

#ifndef EINVAL
#    define EINVAL 22
#endif

/* Frame ids. */
#define EAGLE_TASK_AS_CMD_FRAME_ID (0x100u)
#define EAGLE_TASK_VEH_SPEED_FRAME_ID (0x200u)

/* Frame lengths in bytes. */
#define EAGLE_TASK_AS_CMD_LENGTH (8u)
#define EAGLE_TASK_VEH_SPEED_LENGTH (8u)

/* Extended or standard frame types. */
#define EAGLE_TASK_AS_CMD_IS_EXTENDED (0)
#define EAGLE_TASK_VEH_SPEED_IS_EXTENDED (0)

/* Frame cycle times in milliseconds. */
#define EAGLE_TASK_AS_CMD_CYCLE_TIME_MS (10u)
#define EAGLE_TASK_VEH_SPEED_CYCLE_TIME_MS (10u)

/* Signal choices. */


/* Frame Names. */
#define EAGLE_TASK_AS_CMD_NAME "AS_CMD"
#define EAGLE_TASK_VEH_SPEED_NAME "VEH_SPEED"

/* Signal Names. */
#define EAGLE_TASK_AS_CMD_THROTTLE_REQ_NAME "ThrottleReq"
#define EAGLE_TASK_AS_CMD_BRAKE_REQ_NAME "BrakeReq"
#define EAGLE_TASK_AS_CMD_MISSION_FINISHED_NAME "MissionFinished"
#define EAGLE_TASK_VEH_SPEED_VEHICLE_SPEED_NAME "VehicleSpeed"

/**
 * Signals in message AS_CMD.
 *
 * Longitudinal command from the autonomous system. Send every 10 ms. If no AS_CMD arrives for 200 ms the vehicle triggers the emergency brake.
 *
 * All signal values are as on the CAN bus.
 */
struct eagle_task_as_cmd_t {
    /**
     * Throttle request, 0 = none, 1 = full.
     *
     * Range: 0..1000 (0..1 -)
     * Scale: 0.001
     * Offset: 0
     */
    uint16_t throttle_req;

    /**
     * Brake request, 0 = none, 1 = full.
     *
     * Range: 0..1000 (0..1 -)
     * Scale: 0.001
     * Offset: 0
     */
    uint16_t brake_req;

    /**
     * Set to 1 once the vehicle is at standstill inside the stop zone.
     *
     * Range: 0..1 (0..1 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t mission_finished;
};

/**
 * Signals in message VEH_SPEED.
 *
 * Vehicle speed, sent every 10 ms.
 *
 * All signal values are as on the CAN bus.
 */
struct eagle_task_veh_speed_t {
    /**
     * Range: 0..4000 (0..40 m/s)
     * Scale: 0.01
     * Offset: 0
     */
    uint16_t vehicle_speed;
};

/**
 * Pack message AS_CMD.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int eagle_task_as_cmd_pack(
    uint8_t *dst_p,
    const struct eagle_task_as_cmd_t *src_p,
    size_t size);

/**
 * Unpack message AS_CMD.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int eagle_task_as_cmd_unpack(
    struct eagle_task_as_cmd_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from AS_CMD.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int eagle_task_as_cmd_init(struct eagle_task_as_cmd_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t eagle_task_as_cmd_throttle_req_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double eagle_task_as_cmd_throttle_req_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool eagle_task_as_cmd_throttle_req_is_in_range(uint16_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool eagle_task_as_cmd_throttle_req_is_in_phys_range(double value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t eagle_task_as_cmd_brake_req_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double eagle_task_as_cmd_brake_req_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool eagle_task_as_cmd_brake_req_is_in_range(uint16_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool eagle_task_as_cmd_brake_req_is_in_phys_range(double value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t eagle_task_as_cmd_mission_finished_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double eagle_task_as_cmd_mission_finished_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool eagle_task_as_cmd_mission_finished_is_in_range(uint8_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool eagle_task_as_cmd_mission_finished_is_in_phys_range(double value);

/**
 * Pack message VEH_SPEED.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int eagle_task_veh_speed_pack(
    uint8_t *dst_p,
    const struct eagle_task_veh_speed_t *src_p,
    size_t size);

/**
 * Unpack message VEH_SPEED.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int eagle_task_veh_speed_unpack(
    struct eagle_task_veh_speed_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from VEH_SPEED.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int eagle_task_veh_speed_init(struct eagle_task_veh_speed_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t eagle_task_veh_speed_vehicle_speed_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double eagle_task_veh_speed_vehicle_speed_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool eagle_task_veh_speed_vehicle_speed_is_in_range(uint16_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool eagle_task_veh_speed_vehicle_speed_is_in_phys_range(double value);


#ifdef __cplusplus
}
#endif

#endif
