/**
 * @file eagle_task.c
 *
 * @brief This source file was generated by cantools version 44.1.0 Thu Oct  8 07:06:21 2026.
 *
 * @copyright Copyright (c) 2018-2019 Erik Moqvist
 *
 * @par License
 * The MIT License (MIT)
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use, copy,
 * modify, merge, publish, distribute, sublicense, and/or sell copies
 * of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
 * BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
 * ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

#include <string.h>

#include "eagle_task.h"

static inline uint8_t pack_left_shift_u8(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value << shift) & mask);
}

static inline uint8_t pack_left_shift_u16(
    uint16_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value << shift) & mask);
}

static inline uint8_t pack_right_shift_u16(
    uint16_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value >> shift) & mask);
}

static inline uint16_t unpack_left_shift_u16(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint16_t)((uint16_t)(value & mask) << shift);
}

static inline uint8_t unpack_right_shift_u8(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value & mask) >> shift);
}

static inline uint16_t unpack_right_shift_u16(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint16_t)((uint16_t)(value & mask) >> shift);
}

int eagle_task_as_cmd_pack(
    uint8_t *dst_p,
    const struct eagle_task_as_cmd_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u16(src_p->throttle_req, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(src_p->throttle_req, 8u, 0xffu);
    dst_p[2] |= pack_left_shift_u16(src_p->brake_req, 0u, 0xffu);
    dst_p[3] |= pack_right_shift_u16(src_p->brake_req, 8u, 0xffu);
    dst_p[4] |= pack_left_shift_u8(src_p->mission_finished, 0u, 0x01u);

    return (8);
}

int eagle_task_as_cmd_unpack(
    struct eagle_task_as_cmd_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->throttle_req = unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    dst_p->throttle_req |= unpack_left_shift_u16(src_p[1], 8u, 0xffu);
    dst_p->brake_req = unpack_right_shift_u16(src_p[2], 0u, 0xffu);
    dst_p->brake_req |= unpack_left_shift_u16(src_p[3], 8u, 0xffu);
    dst_p->mission_finished = unpack_right_shift_u8(src_p[4], 0u, 0x01u);

    return (0);
}

int eagle_task_as_cmd_init(struct eagle_task_as_cmd_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct eagle_task_as_cmd_t));

    return 0;
}

uint16_t eagle_task_as_cmd_throttle_req_encode(double value)
{
    return (uint16_t)(value / 0.001);
}

double eagle_task_as_cmd_throttle_req_decode(uint16_t value)
{
    return ((double)value * 0.001);
}

bool eagle_task_as_cmd_throttle_req_is_in_range(uint16_t value)
{
    return (value <= 1000u);
}

bool eagle_task_as_cmd_throttle_req_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 1.0));
}

uint16_t eagle_task_as_cmd_brake_req_encode(double value)
{
    return (uint16_t)(value / 0.001);
}

double eagle_task_as_cmd_brake_req_decode(uint16_t value)
{
    return ((double)value * 0.001);
}

bool eagle_task_as_cmd_brake_req_is_in_range(uint16_t value)
{
    return (value <= 1000u);
}

bool eagle_task_as_cmd_brake_req_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 1.0));
}

uint8_t eagle_task_as_cmd_mission_finished_encode(double value)
{
    return (uint8_t)(value);
}

double eagle_task_as_cmd_mission_finished_decode(uint8_t value)
{
    return ((double)value);
}

bool eagle_task_as_cmd_mission_finished_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool eagle_task_as_cmd_mission_finished_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 1.0));
}

int eagle_task_veh_speed_pack(
    uint8_t *dst_p,
    const struct eagle_task_veh_speed_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u16(src_p->vehicle_speed, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(src_p->vehicle_speed, 8u, 0xffu);

    return (8);
}

int eagle_task_veh_speed_unpack(
    struct eagle_task_veh_speed_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->vehicle_speed = unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    dst_p->vehicle_speed |= unpack_left_shift_u16(src_p[1], 8u, 0xffu);

    return (0);
}

int eagle_task_veh_speed_init(struct eagle_task_veh_speed_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct eagle_task_veh_speed_t));

    return 0;
}

uint16_t eagle_task_veh_speed_vehicle_speed_encode(double value)
{
    return (uint16_t)(value / 0.01);
}

double eagle_task_veh_speed_vehicle_speed_decode(uint16_t value)
{
    return ((double)value * 0.01);
}

bool eagle_task_veh_speed_vehicle_speed_is_in_range(uint16_t value)
{
    return (value <= 4000u);
}

bool eagle_task_veh_speed_vehicle_speed_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 40.0));
}
